### ISSUE TITLE
Second click doesn't work

### ISSUE THREAD

**Issue by wordica** [davist11/jQuery-One-Page-Nav#118]
I add this plugin. Works good but if I click on button, it scroll down to section. Then I move page manually to top and trying to click second time on that same button - and nothing. Plugin doesn't work on second click. Every button work only once.

Maybe some more comment. Sometimes it doesn't work at all for second click and sometime it doesn't work only for button "opposite" last clicked button (clicked before this new). When I click some other button - "opposite" start working.

**Comment by MichaelJCole** [comment]
I was able to change this with out using a fork.

I wanted blog posts to highlight the current link, but clicking "Blog" to go to the index.  

I was adding the current class myelf.  Then, *after* Initializing navbar plugin, create a click event handler on the link you want to change.

```
$( '#header-nav' ).onePageNav({
	scrollSpeed : 1000,
	changeHash: true,
	filter : ':not(.external)',
	begin : function() {
		$( '#navigation' ).collapse( 'toggle' );
	},
  });

  // Hack for navbar
  $('#blogLink').on('click', function() {
    window.location = '/articles';
  });
```

**Comment by aareyad** [comment]
Solved the issue.

Thank You
