### ISSUE TITLE
JQuery One Page Issue

### ISSUE THREAD

**Issue by rawadm** [davist11/jQuery-One-Page-Nav#129]
I seem to be having an issue. For some reason the JQuery isn't working. I know it's something to do with JQuery file, I just can't figure out what the problem is.

<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Untitled</title>
    </head>
    <body>

      <ul id="nav">
        <li class="current"><a href="#home">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#work">Work</a></li>
      </ul>

      <div id="home">
        <strong>Home</strong>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div id="about">
        <strong>About</strong>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div id="work">
        <strong>Work</strong>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>  

        <script src="http://code.jquery.com/jquery-latest.min.js"></script>
        <script src="jquery.scrollTo.js"></script>
        <script src="jquery.nav.js"></script>
        <script type="text/javascript">

          s$(document).ready(function() {
            $('#nav').onePageNav();
          });

        </script>
        
    </body>
</html>

**Comment by davist11** [comment]
Do you have a link to your page where it isn't working?

**Comment by rawadm** [comment]
I only have it running on a local host. I can record a video and show you exactly whats going on.

**Comment by rawadm** [comment]
Here is the live code. I think It's actually work, however the smooth effect isn't
http://codepen.io/anon/pen/wBqgBz

**Comment by davist11** [comment]
None of the JS files are linked up in the codepen.

**Comment by rawadm** [comment]
Oh yeah that's true, sorry I just woke up.

**Comment by rawadm** [comment]
@davist11 Now the JQuery files are included on Codepen.
http://codepen.io/anon/pen/wBqgBz

**Comment by davist11** [comment]
Looks like it's working to me.

**Comment by rawadm** [comment]
@davist11 I got it working. I was missing the JQuery.nav.js file.
