### ISSUE TITLE
Bug with Bootstraps Navbar

### ISSUE THREAD

**Issue by netzstrand** [davist11/jQuery-One-Page-Nav#147]
Hi Davist and thanks for your great script!
I have found a small bug with big impact on my small project :/
I'm using your script with bootstraps (latest version) and I have a top navigation splited into left and right, like this example here:
*nav*
*ul class navbar-left* 
*li* *a*
*li* *a*
*li* *a*
*/ul*
*ul class navbar-right*
*li* *a*
*li* *a*
*li* *a*
*/ul*
* / nav*			

If my "current"-class position is on the upper ul and I click a link in the ul below, the current class does not disappear from the last element of the first nav. So, now I have two current classes in my nav and I'm not longer able to click on the last link from the first ul. The same thing happens, if I click the vice versa.

It would be super cool, if you could help me here out. Can you show me a workaround or fix this at all?

Best regards,
Chris
(sorry for my english, I'm not a nativ speaker...)

**Comment by davist11** [comment]
Is there a way to combine into a single `<ul>`?

**Comment by netzstrand** [comment]
Not realy. because in the center of the nav is a brand-logo(between the to ul).

**Comment by davist11** [comment]
At the moment, you won't be able to use this plugin without modifying it.

**Comment by netzstrand** [comment]
Is it diffcult to modify? I'm not in love with js :/

**Comment by davist11** [comment]
Not terribly difficult. Actually, you could try calling `onePageNav` on the `<nav>` element instead of the `<ul>` and that should work.

**Comment by netzstrand** [comment]
Ok, I initialize $('.navbar-collapse').onePageNav() and navbar-collapse is one of my nav classes, but it does not fix the problem. I fear, that I missunderstood you.

**Comment by davist11** [comment]
I don't follow. Do you have a link?

**Comment by netzstrand** [comment]
http://netzstrand.de/projekte/wattenloeper/index.php?site=#welcome

**Comment by davist11** [comment]
Everything appears to be working correctly to me

**Comment by netzstrand** [comment]
try this:
1) click "Cuxhaven"
2) click "Impressionen"
3) click "Cuxhaven"  <<< does not work anymore
4) click somewhere else, like "Geschichte"
5) click "Cuxhaven" <<< now this works again
6) click "Impression" <<< does not work
...and so on

**Comment by davist11** [comment]
That works fine for me.

**Comment by netzstrand** [comment]
okay, after I restart my browser the issue is gone, so your first fix with the <nav> tag solves the problem. Sorry for the complications and thanks a lot for your effort. Really kind of you :)
