### ISSUE TITLE
How can i implement section scroll when click only one link

### ISSUE THREAD

**Issue by Nur-jaman** [davist11/jQuery-One-Page-Nav#158]
Hi,
Many thanks for create this nice plugin :)

How can i implement section scroll when click only one link. Please check attachment image here http://prnt.sc/dibnx5
When i will click on this arrow it will go to next section and again when i click then go next section. mean per click per section

Many thanks in advance

**Comment by davist11** [comment]
That would have to be some custom javascript where you would trigger a click on the next section

**Comment by Nur-jaman** [comment]
can you help please ? :( 

i really need to achieve this

**Comment by davist11** [comment]
Sorry, I don't have the time to write custom solutions for everyone, but it would be something like:

```
$('.next-button').on('click', function(e) {
	e.preventDefault();

	var $next = $('#nav').find('.current').next();
	$next.find('a').trigger('click');
});
```
