### ISSUE TITLE
Check license 

### ISSUE THREAD

**Issue by sufuf3** [davist11/jQuery-One-Page-Nav#159]
Hi @davist11,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we're add the license of this library.

I found that the license for this repo are `MIT` and `GPL`.
And Could you please tell me which version of `GPL` license you use exactly?
Thank you.

[cdnjs/cdnjs#10197](https://github.com/cdnjs/cdnjs/pull/10197)

**Comment by Ninetheme** [comment]
Hi

I'm not sure about it , i am beginner on github.

**Comment by davist11** [comment]
I just added a license file: https://github.com/davist11/jQuery-One-Page-Nav/blob/master/LICENSE

**Comment by sufuf3** [comment]
@davist11 Thank you.
I'd like to confirm that the license of this library is just under the MIT, isn't it?

**Comment by davist11** [comment]
Correct, I just added the license file to the repo

**Comment by sufuf3** [comment]
Thank you.
