### ISSUE TITLE
How to set the offset without editing jquery.nav.js?

### ISSUE THREAD

**Issue by Alecto** [davist11/jQuery-One-Page-Nav#162]
I need 40px offset from top.
Is there any way to customize this option?
Something like this
      $('#navbar').onePageNav({
      	'scrollOffset': 117
      });

**Comment by davist11** [comment]
Check out this demo

http://davist11.github.io/jQuery-One-Page-Nav/top.html

**Comment by Alecto** [comment]
I can not use indentations; this is not allowed in the design.
As a result, the menu closes part of the section.
The ideal way is to offset, but for this i need to edit the library.

**Comment by davist11** [comment]
It has zero impact on the design if you use a negative top margin and top padding.

**Comment by Alecto** [comment]
As I said, this method can not be applied, because in the design of the section template have different predefined indents, changing which is prohibited design requirements.
Why do not you want to add this option to the plugin? Because I'm not the first one to whom this option is necessary.

**Comment by davist11** [comment]
I'm not sure what predefined indents means. I do not want to add it back to the plugin because it is more complexity to add, you can't change the value across sections, and you can't adjust it responsively. Using a CSS approach simplifies and solves all of this easily.
