### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by md-ataur** [davist11/jQuery-One-Page-Nav#170]
Thanks for your plugin, it is really great.

**Issue description:**
The problem is when i click the menu then showing this message 
"Uncaught TypeError: Cannot read property 'top' of undefined"

Demo Link: http://onlivetech.com/

Thanks and Regards

**Comment by davist11** [comment]
It doesn't look like you have the navigation set to jump to specific sections on the page. You need to use hashes and ids

```
<ul>
    <li><a href="#team">Team</a></li>
    ....
</ul>

<div id="team">
    ...
</div>
```

**Comment by md-ataur** [comment]
Hi,
I added hash on the menu id for specific sections. It's ok when i set the hashes on menu id but when i click the blog menu then same problem is showing.

Demo Link: http://onlivetech.com/blog/

Thanks

**Comment by davist11** [comment]
I think you are misunderstanding how the plugin works. If all of your links are going to be external, then there isn't a point to using the plugin. It's for jumping between sections on a single page: http://davist11.github.io/jQuery-One-Page-Nav/

**Comment by md-ataur** [comment]
Now I got it 
Thank you so much
