### ISSUE TITLE
library not working with other tech

### ISSUE THREAD

**Issue by Abhijeetrkushwaha** [davist11/jQuery-One-Page-Nav#175]
I would like to use the plugin but i think there might be a issue when i used it with other library
![image](https://user-images.githubusercontent.com/62172015/103116133-52e3ee80-468b-11eb-98a4-1cdd67b27fea.png)

any suggestion

**Comment by davist11** [comment]
I would need to have a better understanding of what libraries you are adding.

Also, this plugin hasn't been updated in 3 years, so another solution may be a better option.

**Comment by Abhijeetrkushwaha** [comment]
Hey I had figured out the issue and it's working really well... thank you so much for looking into the issue 🙂.
