### ISSUE TITLE
Change URL hash on scrolling

### ISSUE THREAD

**Issue by funch** [davist11/jQuery-One-Page-Nav#21]
Can one get the url to change when scrolling as it does when clicking on the links?
It is quite a big deal breaker when using hashtags as we want to make the page linkable.

**Comment by ixlipixli** [comment]
This worked for me:

		adjustNav: function(self, $parent) {
			self.$elem.find('.' + self.config.currentClass).removeClass(self.config.currentClass);
			$parent.addClass(self.config.currentClass);
			
			**var link= $parent.attr('data-menuanchor');
			var newLoc = '#' + link;
			
			if(self.config.changeHash) {
				history.pushState(1,1,newLoc);
			}**
		}
