### ISSUE TITLE
another uncaught typeerror: cannot read property 'top' of null plugins.js:223

### ISSUE THREAD

**Issue by eshansen** [davist11/jQuery-One-Page-Nav#22]
Hi, 

I originally just dropped your plugin into my code and it worked beautifully, I only noticed this was happening when I tried to implement a bit more js code using jquery, and basically nothing was happening.

The site is on my localhost at the moment but Id be happy  to send you the html and css.  Im new to github so not sure best way of pinging that across to you.

the full error was as below - 
Uncaught TypeError: Cannot read property 'top' of null plugins.js:223
OnePageNav.getPositions plugins.js:223
e.extend.each jquery.min.js:2
e.fn.e.each jquery.min.js:2
OnePageNav.getPositions plugins.js:221
OnePageNav.init plugins.js:171
$.fn.onePageNav plugins.js:311
e.extend.each jquery.min.js:2
e.fn.e.each jquery.min.js:2
$.fn.onePageNav plugins.js:310

That line turns out to be the last line of this bit:
self.$nav.each(function() {
                linkHref = self.getHash($(this));
ie here-->              topPos = $('#' + linkHref).offset().top;

Thanks for any help you can offer

**Comment by as88425** [comment]
Hey @eshansen  i'm getting this error in console :> 'Uncaught TypeError: Cannot read property 'top' of undefined .

when i clicked on this error it's reached me topPos = $('#' + linkHref).offset().top; this line .
Please help me out .
Thanks in advance .

**Comment by davist11** [comment]
That most likely means you have an item in your navigation that doesn't match up to a section on the page.
